### ISSUE TITLE
Getting the permissions of a user

### ISSUE THREAD

**Issue by piedoom** [zeyla/serenity#119]
I'm creating a bot that needs to make sure that the calling user has specific `Permissions`.  How would one do this in a command?  I haven't found a related field on the `User` struct and can't find documentation on how to do so.  

It seems like you could call something like `.ban_members()` with the `Permissions` struct after getting permissions, however the User does not seem to contain permission data.

Thanks.

**Comment by acdenisSK** [comment]
A `User` from discord's perspective does not have *any* permissions (although they do have some permissions in a dm session), but a `Member` does.

So to get the permissions for a member, just use [`Member::permissions`](https://docs.rs/serenity/0.3.0/serenity/model/struct.Member.html#method.permissions). (If you don't know how to get a member from an id, [here's how](https://docs.rs/serenity/0.3.0/serenity/cache/struct.Cache.html#method.member))

By the way, this is not really the place to get help like this, instead join the [discord server here](https://discord.gg/PgQYQcc).

**Comment by piedoom** [comment]
Thanks for the help, and sorry for asking in the wrong place.  Totally missed the server link.
