### ISSUE TITLE
Allow explicit disconnect

### ISSUE THREAD

**Issue by blaenk** [zeyla/serenity#124]
I've been prototyping a bot in first Javascript, then Go, then Rust with Discord.rs and now Serenity and all prior libraries I used allowed me to cleanly, explicitly shutdown/disconnect the connection(s), which I did for example when the application received a SIGINT or whenever else I felt it to be useful.

As far as I know this library doesn't currently have the ability to do this, which means that when I terminate the application I still see the bot in my server for a while until it times out.

**Comment by acdenisSK** [comment]
Well, this is already implemented with [4d4e9dcf](https://github.com/zeyla/serenity/commit/4d4e9dcf4b559423dd5b169ecef46efe6a0d1fca). Which, if you're wondering, is indeed a hack. But couldn't think of any other solution, as once the client boots the shards up, it passes them onto `(monitor/handle)_shard`, removing the direct access. Still, should be prominent enough.

**Comment by blaenk** [comment]
Thanks! Should work fine enough.
