### ISSUE TITLE
Allow direct playing of pre-encoded Opus audio

### ISSUE THREAD

**Issue by blaenk** [zeyla/serenity#125]
It would be nice if there were a built-in way to directly play correctly pre-encoded Opus, to avoid having to spawn and involve ffmpeg unnecessarily.

This was also requested of discord-rs and someone [filed a PR](https://github.com/SpaceManiac/discord-rs/pull/68) but it was never merged, in case its code may be useful.

**Comment by acdenisSK** [comment]
Implemented in #148
