### ISSUE TITLE
Compile time error on example 07

### ISSUE THREAD

**Issue by hurnhu** [zeyla/serenity#136]
I have just tried to build 07_sample_bot_structure, when trying to compile i get the following error:

```
Compiling timeBot v0.1.0 (file:///C:/Users/Micheal%20Bolton/Downloads/serenity-master%20(1)/serenity-master/examples/07_sample_bot_structure)
error[E0599]: no method named `unwrap` found for type `parking_lot::mutex::MutexGuard<'_, serenity::gateway::Shard>` in the current scope
 --> src\commands\meta.rs:3:10
  |
3 |         .unwrap()
  |          ^^^^^^

error: aborting due to previous error
```

I am compiling on windows 10, can confirm other rust programs compile with no errors.

Tested on: 
rust latest nightly (win 10 env)
AND
rust  1.5.0 (92d0d1e9e 2017-06-24) linux (ubuntu 14) env

This problem is also present is other examples

**Comment by Avighnash** [comment]
Got nearly the same error. https://cdn.discordapp.com/attachments/253635665344987136/346734827351048192/Screen_Shot_2017-08-14_at_12.20.45_PM.png

**Comment by acdenisSK** [comment]
[e00fe3a](https://github.com/zeyla/serenity/commit/e00fe3ad9e1853443c8905da934ea3983813af89) should fix this. And sorry, examples are on the bottom of my priority list currently, so it's far more likely for them to be abandoned from being updated for a while.
