### ISSUE TITLE
Revamp the arg usage with an `Args` struct that provides a nifty api

### ISSUE THREAD

**Issue by acdenisSK** [zeyla/serenity#142]
Also another idea from @fwrs.
Its api would be in the lines of:
`single`: Removes and returns the first element of the internal vector, but also adds parsing functionality, e. g
```rust
// The internal vector is ["42", "69"]
let num = args.single::<i32>();
num == 42i32 // this would return `true`
// The vector is also now ["69"]
```
`skip`: Obviously skips ~~removes~~, but behaves kinda like `mem::replace` in that it returns the skipped part of the vector.
`single_quoted`: Like `single`, but takes quotes into account.
And many more for getting the rest of the vector and such.

I already layed out an implementation (edit: added `full`, `single_n`, `single_quoted_n`. the `_n` methods are like their regular counterparts, but not modify the vector) [here](https://play.rust-lang.org/?gist=0da17b3cedcc95783204bf7a311f27d0&version=stable).

cc @zeyla, i'm fairly sure you'd like this

**Comment by zeyla** [comment]
👍
