### ISSUE TITLE
[meta] Roadmap to v0.4.0

### ISSUE THREAD

**Issue by zeyla** [zeyla/serenity#155]
It's been a couple months since a release, we should see what's still needed. Are there any crucial features or bugs needing to be fixed?

#60 is more of a v0.5.0 issue since I don't plan on finishing this in the next week.

**Comment by Roughsketch** [comment]
I'm going to comment this here as well, but I think I've found out why the websocket library occasionally spams opcode errors. I've posted what I've found [on the issue](https://github.com/cyderize/rust-websocket/issues/137), but the current maintainer hasn't responded yet. I've tried to fix it myself but I can't find an elegant way to handle it, so I'm waiting on his response.

Anyway, I think it might be beneficial to wait at least a few days to see if that bug gets patched before pushing a new crate version.

**Comment by zeyla** [comment]
I agree, would be good to see if this can be patched soon before a release.

**Comment by lolzballs** [comment]
If 0.4.0 is waiting on a patch for that, it may be a good idea to release a small update before 0.4.0 since categories seem to break the library now.

**Comment by zeyla** [comment]
We're testing a custom fork of rust-websocket that fixes the issues, and now that we have a multi-sharding fix pushed, v0.4 should be ready to go. I'm just writing the changelog for it, should see a release in the next couple of days.

**Comment by zeyla** [comment]
Closed by 0fcf1d3, v0.4.0 has [been released](https://crates.io/crates/serenity) on crates.io. You can read the release details [here](https://github.com/zeyla/serenity/releases/tag/v0.4.0).
