### ISSUE TITLE
Change the builders to mutably-borrow themselves

### ISSUE THREAD

**Issue by acdenisSK** [zeyla/serenity#159]

**Comment by putterson** [comment]
I'd be interested in picking this up for hacktoberfest. Is this about changing the builders from creating new instances of themselves to instead mutably borrow a reference to themselves which they mutate?

**Comment by acdenisSK** [comment]
Just a change from `fn abc(self, ...) -> Self` to `fn abc(&mut self, ...) -> &mut Self` really.
And changing closures that're using the builders to account for that as well.

**Comment by putterson** [comment]
Does my approach look along the lines of what you were thinking? I had to add a build function to get an owned instance. The GetMessages impl is its own builder, which seems a little wonky. Just wanted to check in before proceeding further.

**Comment by acdenisSK** [comment]
Close, but i meant by the closures to accept `&mut Builder` *and* return `&mut Builder`, not an immutable borrow to the builder as that would kill off this issue's meaning.

Also for `GetMessages`, you needn't clone it, but more like do `let map = &mut builder.0;`, as inside `messages` it does not move the map itself or anything, it just removes a few things from it.
(Plus i don't think we'd really need to be cloning the builder itself if the `serde_json::Map` inside of it is what matters to us)

**Comment by zeyla** [comment]
Closed by 420b8d8.
