### ISSUE TITLE
Refactor functions with update syntax

### ISSUE THREAD

**Issue by fwrs** [zeyla/serenity#161]
For example code in https://github.com/zeyla/serenity/blob/d925f926c0f9f5b8010a998570441258417fc89a/src/framework/standard/command.rs#L74-L94 could be done like

```rs
Command {
    exec: CommandType::Basic(Box::new(f)),
    help_available: true,
    required_permissions: Permissions::empty(),
    .. Default::default(),
}
```

I'm sure there are other places where this can be used

** derive Default first

**Comment by efyang** [comment]
Could I take this?

**Comment by zeyla** [comment]
Absolutely, thanks

**Comment by zeyla** [comment]
Closing because I'd prefer not to take the penalty cost of using this syntax.
