### ISSUE TITLE
crates.io 0.3.0 missing required fields

### ISSUE THREAD

**Issue by BrayVoid** [zeyla/serenity#163]
According to [Discord developers website - as of August 16 2017](https://discordapp.com/developers/docs/change-log#august-16-2017-%E2%80%94-breaking-change):
> The type field in the game object for Gateway Status Update and Presence Update payloads is no longer optional when the game object is not null.
In this repo _src/gateway/shard.rs_ (line 906) contains the following code:
```
let msg = json!({
    "op": OpCode::StatusUpdate.num(),
    "d": {
        "afk": afk,
        "since": now,
         "status": status.name(),
         "game": game.as_ref().map(|x| json!({
            "name": x.name,
            "type": x.kind,
            "url": x.url,
        })),
    },
});
```
This code has the required "type" field.

In version 0.3.0 on crates.io, _src/gateway/shard.rs_ (line 897) contains the following code:
```
let msg = json!({
    "op": OpCode::StatusUpdate.num(),
    "d": {
        "afk": afk,
        "since": now,
        "status": status.name(),
        "game": game.as_ref().map(|x| json!({
            "name": x.name,
        })),
    },
});
```

This causes only the `status` and `afk` fields _[[here]](https://discordapp.com/developers/docs/topics/gateway#gateway-status-update-gateway-status-update-structure)_ to be updated as `game` is missing the now required _[type](https://discordapp.com/developers/docs/topics/gateway#game-object-game-structure)_ field.
***
Ideally the section on line 897 of _src/gateway/shard.rs_ from crates.io would match the section on line 906 on this repo to restore the game setting functionality.

I would consider this a bug as it prevents a bot having its game set, also without the x.kind and x.url fields how did GameType::Streaming work before (if it did)?

**Comment by acdenisSK** [comment]
It is a bug indeed, but since cargo won't allow me to modify a version's code or something, you'll have to wait once 0.4 comes out.
Although in regards to `GameType::Streaming`, i don't think that it did even.
