### ISSUE TITLE
Expected Args.single_quoted behaviour

### ISSUE THREAD

**Issue by jhelwig** [zeyla/serenity#180]
From the documentation of `Args.single_quoted` it looked like it would handle grabbing `first argument` from a command like `!command "first argument" second`, but it ends up grabbing `first`.

`single_quoted` is passing the first element of `delimiter_split` to `parse_quotes`, and since the delimiter is `" "`, by the time `single_quoted` gets to look at anything, all it has to work with is `"first`.

What is the expected usage, and behavior of `Args.single_quoted`?

**Comment by jhelwig** [comment]
I'd say this isn't so much a general question as a bug report, or pointing out insufficient documentation. :) From how `Args.single_quoted` is documented, the current behavior is a bug.

**Comment by acdenisSK** [comment]
*Well*, i was a bit lazy on updating `parse_quotes` so that it's more intelligent on its output which `Args` could rely on for `single_quoted` (And have the initially passed input stored in `Args`, instead of doing `delimiter_split.join(delimiter)` to make that part for it more better as well).

But yeah, it's supposed to be taking the first quoted item in the message, remove the quotes, then parse it to some type you specified.

**Comment by jhelwig** [comment]
Storing the initially passed input in `Args` seems like it would be a pain to keep in sync with the split version. Were you thinking of not storing the `delimiter_split` version at all, and modifying the argument methods to dynamically parse the input string (and potentially removing the parsed argument from it) as needed using `delimiter` or `parse_quotes`?

I'm happy to work on a PR for this, I just wanted to make sure we were on the same page about the approach you had in mind.

**Comment by acdenisSK** [comment]
That could probably work better, but not sure about how it'd affect performance.
Still, you're free to make a pr for this.

**Comment by jhelwig** [comment]
How it would affect performance probably depends a lot on the discussion happening in #181.

**Comment by acdenisSK** [comment]
Not really, because if we changed from `delimiter_split: Vec<String>` to just `input: String`, then we'd start getting to some problems when modifying a specific part of the string; aka with `self.input.split(self.delimiter)`, `input.next().map(|s| s.parse::<T>()...)` and `self.input = input.collect()` and such being done constantly in `Args`'s api.
Which is a bound railway to performance hell.

**Comment by jhelwig** [comment]
My comment was more about whether `delimiters` should be "use the first found token from the list to split the entire input string into arguments" or "all tokens in the list should be use for splitting", but that was a false-start since I think we're both in agreement that once one of the delimiters is found (after trying them in order), that's the one that should be used for the entire string.

**Comment by acdenisSK** [comment]
Oh. But yeah, we are.

**Comment by jhelwig** [comment]
I'm pretty sure there are more efficient ways to do it than with doing `self.input.split(self.delimiter)`, `input.next().map(|s| s.parse::<T>()...)` and `self.input = input.collect()` all over the place. I'll work on a PR for it.

**Comment by jhelwig** [comment]
Working on the PR I noticed that `Args.multiple_quoted`, and `Args.list` both take `self` instead of `&self`. Is this intentional?

https://github.com/zeyla/serenity/blob/2d6a150a348860a2247e1c248ffd072f03f8e1dc/src/framework/standard/args.rs#L146
https://github.com/zeyla/serenity/blob/2d6a150a348860a2247e1c248ffd072f03f8e1dc/src/framework/standard/args.rs#L159

**Comment by fwrs** [comment]
yea it's intentional because iterator becomes useless after calling those methods, though I don't like that those two methods are named inconsistently

**Comment by jhelwig** [comment]
I spiked out some changes to the argument parsing to get quoted arguments working, but in the process I noticed some nasty edge cases around "use the first found token from the list to split the entire input string into arguments" that means I don't think it's a viable path to continue down. The following is intended to have all delimiters "active" at all times.

The current behavior leads to potentially very surprising behavior with an argument string along the lines of `"Hello, world" with more here` with `delimiters(vec![", ", " "])`. If a user were to call `single_quoted` repeatedly, it's not unreasonable for them to expect to get back `["Hello, world", "with", "more", "here"]`, which is not at all what would happen with the current behavior. If a user is calling `single`, then they are expecting quotes to be ignored, so it would be reasonable to get `"Hello` back as the first argument. Because of this ambiguity, I feel that determining which delimiter to use, must be delayed until the user asks for the next argument from the argument string, meaning that the "all tokens in the list should be use for splitting" option is the one that results in the least surprising behavior.

There are some other restrictions around quoted arguments compared to [the test I saw for `parse_quotes`](https://github.com/zeyla/serenity/blob/v0.4.3/tests/test_parsers.rs#L37-L41):
* `single_quoted_arg` will only consider an argument to be quoted if a double quote is the next remaining unparsed character. If a double quote is not the next character in the argument stream, then it will behave the same as `single_arg`.
* The quoted argument _must_ be in a double quote either: 1) followed by one of the configured delimiters, or 2) be final character in the argument string.

I felt that these restrictions resulted in a lot less surprising behavior compared to the behavior shown in the test. Especially since the method is supposed to remote the quotes for the argument. The other option would have been to have something more akin to Bash's handling of quotes, and it did not seem reasonable to expect end-users of bots to know & understand all of the rules of how that works.

The idea is that `Args` would update its internal store using the "rest" portion of the `IResult` that comes back from `single_arg`, and `quoted_single_arg` as well as parsing the `&str`/`String` into the type that the user requested.

I do not intended to carry this spike forward any further, but I am happy to answer any questions, and for people to use the spike below as they see fit.

<details>
<summary>Arg parser spike</summary>

`Cargo.toml`:

```rust
[dependencies.nom]
version = "3.2.0"
features = ["verbose-errors"]
```

```rust
use nom::{AsBytes, AsChar, ErrorKind, IResult, InputIter, InputLength, Needed, Slice};

use std::ops::{Range, RangeFrom, RangeTo};
use std::str;
use std::string::String;

fn non_quote_special<T>(input: T) -> IResult<T, T>
    where T: Slice<Range<usize>> + Slice<RangeFrom<usize>> + Slice<RangeTo<usize>>,
          T: InputIter + InputLength,
          <T as InputIter>::Item: AsChar
{
    let input_length = input.input_len();
    if input_length == 0 {
        return IResult::Incomplete(Needed::Unknown);
    }

    for (idx, item) in input.iter_indices() {
        let item_char = item.as_char();
        if item_char == '"' || item_char == '\\' {
            if idx == 0 {
                return IResult::Error(error_position!(ErrorKind::IsNot, input));
            } else {
                return IResult::Done(input.slice(idx..), input.slice(0..idx));
            }
        }
    }
    IResult::Done(input.slice(input_length..), input)
}

fn separator<T>(input: T, delimiter: &Vec<String>) -> IResult<T, T>
    where T: Slice<Range<usize>> + Slice<RangeFrom<usize>> + Slice<RangeTo<usize>>,
          T: AsBytes + Clone + InputLength
{
    if input.input_len() == 0 {
        return IResult::Incomplete(Needed::Unknown);
    };

    let input_copy = input.clone();
    let input_str = match str::from_utf8(input_copy.as_bytes()) {
        Ok(s) => s,
        Err(_) => return IResult::Error(error_position!(ErrorKind::IsNotStr, input)),
    };
    for sep in delimiter {
        if input_str.starts_with(sep.as_str()) {
            return IResult::Done(input.slice(sep.len()..), input.slice(..sep.len()));
        }
    }

    return IResult::Error(error_position!(ErrorKind::NoneOf, input));
}

fn delimiter<'a>(input: &'a [u8], delimiters: &Vec<String>) -> IResult<&'a [u8], &'a [u8]> {
    use nom::{IResult, Slice};

    let mut sep_len = None;

    for sep in delimiters {
        if input.starts_with(sep.as_bytes()) {
            sep_len = Some(sep.len());
            break;
        }
    }

    match sep_len {
        Some(l) => IResult::Done(input.slice(0 + l..), input.slice(0..l)),
        None => IResult::Error(error_position!(ErrorKind::Custom(1), input)),
    }
}

fn is_delimiter(input: &[u8], delimiters: &Vec<String>) -> bool {
    match peek!(input, call!(delimiter, delimiters)) {
        IResult::Done(_, _) => true,
        _ => false,
    }
}

fn take_until_delimiter<'a>(input: &'a [u8],
                            delimiters: &Vec<String>)
                            -> IResult<&'a [u8], &'a [u8]> {
    {
        use nom::{InputLength, Slice};

        for n in 0..input.input_len() {
            if is_delimiter(input.slice(n..), delimiters) {
                let res: IResult<_, _> = IResult::Done(input.slice(n..),
                                                       input.slice(..n));
                return res;
            }
        }

        IResult::Done(input.slice(input.len()..), input)
    }

}

fn single<'a>(input: &'a [u8], delimiters: &Vec<String>) -> IResult<&'a [u8], &'a str> {
    if input.input_len() == 0 {
        return IResult::Incomplete(Needed::Unknown);
    }

    map_res!(input,
             do_parse!(
        arg: call!(take_until_delimiter, delimiters) >>
        (arg)
    ),
    str::from_utf8)
}

fn single_string<'a>(input: &'a [u8], delimiters: &Vec<String>) -> IResult<&'a [u8], String> {
    match single(input, delimiters) {
        IResult::Done(r, s) => IResult::Done(r, s.to_string()),
        IResult::Error(e) => IResult::Error(e),
        IResult::Incomplete(i) => IResult::Incomplete(i),
    }
}

pub fn single_arg<'a>(input: &'a [u8], delimiters: &Vec<String>) -> IResult<&'a [u8], &'a str> {
    if input.input_len() == 0 {
        return IResult::Incomplete(Needed::Unknown);
    }

    do_parse!(input,
        arg: call!(single, delimiters) >>
        alt!(eof!() | call!(delimiter, delimiters)) >>
        (arg)
    )
}

fn quoted<'a>(input: &'a [u8]) -> IResult<&'a [u8], String> {
    map_res!(input, do_parse!(
        arg: delimited!(
            char!('"'),
            escaped_transform!(
                call!(non_quote_special),
                '\\',
                alt!(
                    tag!("\\") => { |_| &b"\\"[..] } |
                    tag!("\"") => { |_| &b"\""[..] }
                )),
            char!('"')) >>
        (arg)
    ),
    String::from_utf8)
}

pub fn single_quoted_arg<'a>(input: &'a [u8], delimiters: &Vec<String>) -> IResult<&'a [u8], String> {
    do_parse!(input,
        arg: alt!(call!(quoted) | call!(single_string, delimiters)) >>
        alt!(eof!() | call!(delimiter, delimiters)) >>
        (arg)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_delimiter() {
        assert_eq!(delimiter("".as_bytes(), &vec![" ".to_string()]),
                   IResult::Error(error_position!(ErrorKind::Custom(1), "".as_bytes())));
        assert_eq!(delimiter(" rest".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("rest".as_bytes(), " ".as_bytes()));
    }

    #[test]
    fn test_single_arg() {
        assert_eq!(single_arg("".as_bytes(), &vec![" ".to_string()]),
                   IResult::Incomplete(Needed::Unknown));
        assert_eq!(single_arg("single".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("".as_bytes(), "single"));
        assert_eq!(single_arg("one two".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("two".as_bytes(), "one"));

        assert_eq!(single_arg("one,big,arg".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("".as_bytes(), "one,big,arg"));

        assert_eq!(single_arg("one two, three".as_bytes(),
                              &vec![", ", " "].iter().map(|d| d.to_string()).collect()),
                   IResult::Done("two, three".as_bytes(), "one"));
        assert_eq!(single_arg("two, three".as_bytes(),
                              &vec![", ", " "].iter().map(|d| d.to_string()).collect()),
                   IResult::Done("three".as_bytes(), "two"));

        assert_eq!(single_arg("\"one two\"".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("two\"".as_bytes(), "\"one"));
    }

    #[test]
    fn test_single_quoted_arg() {
        assert_eq!(single_quoted_arg("".as_bytes(), &vec![" ".to_string()]),
                   IResult::Incomplete(Needed::Size(1)));
        assert_eq!(single_quoted_arg("single".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("".as_bytes(), "single".to_string()));
        assert_eq!(single_quoted_arg("one two".as_bytes(), &vec![" ".to_string()]),
                   IResult::Done("two".as_bytes(), "one".to_string()));

        assert_eq!(single_quoted_arg("\"quoted arg\" with more".as_bytes(),
                                     &vec![" ".to_string()]),
                   IResult::Done("with more".as_bytes(), "quoted arg".to_string()));
        assert_eq!(single_quoted_arg("\"quoted with \\\" escaped\" more".as_bytes(),
                                     &vec![" ".to_string()]),
                   IResult::Done("more".as_bytes(), "quoted with \" escaped".to_string()));
        assert_eq!(single_quoted_arg("\"quote does not end".as_bytes(), &vec![" ".to_string()]),
                   IResult::Incomplete(Needed::Size(20)));
    }

    #[test]
    fn test_quoted() {
        assert_eq!(quoted(&b""[..]), IResult::Incomplete(Needed::Size(1)));

        assert_eq!(quoted(&b"\"quoted thing\" lkj lkj lkj lkj lkj lkj "[..]),
                   IResult::Done(&b" lkj lkj lkj lkj lkj lkj "[..], "quoted thing".to_string()));

        assert_eq!(quoted(&b"no quotes here"[..]),
                   IResult::Error(error_position!(ErrorKind::Char, "no quotes here".as_bytes())));
    }

    #[test]
    fn test_separator() {
        assert_eq!(separator("", &vec![" ".to_string()]),
                   IResult::Incomplete(Needed::Unknown));
        assert_eq!(separator(" ", &vec![" ".to_string()]),
                   IResult::Done("", " "));
        assert_eq!(separator(" word", &vec![" ".to_string()]),
                   IResult::Done("word", " "));
        assert_eq!(separator(", word",
                             &vec![", ", " "].iter().map(|d| d.to_string()).collect()),
                   IResult::Done("word", ", "));
    }
}
```

</details>

**Comment by acdenisSK** [comment]
Fixed in [065624](https://github.com/zeyla/serenity/commit/06562435343be7241c0efad3a70a7eff19e3bdc6)
