### ISSUE TITLE
Getting user's voice channel from text message.

### ISSUE THREAD

**Issue by teamplz** [zeyla/serenity#186]
How do you get a users current voice channel from a text message?

**Comment by acdenisSK** [comment]
Firstly, you'll need a [`Guild`](https://docs.rs/serenity/0.4.0/serenity/model/struct.Guild.html); which you can get by using [`Message::guild`](https://docs.rs/serenity/0.4.0/serenity/model/struct.Message.html#method.guild). Afterwards, you'll need to do a lookup in [`Guild::voice_states`](https://docs.rs/serenity/0.4.0/serenity/model/struct.Guild.html#structfield.voice_states) with `voice_states.get(&message.user.id)`. Then finally, with [`VoiceState::channel_id`](https://docs.rs/serenity/0.4.0/serenity/model/struct.VoiceState.html#structfield.channel_id) you can start messing with it to your heart's content.

summary:
```rust
let guild = message.guild().unwrap_or_else(|| panic!("Guild not found"));
let guild = guild.read().unwrap();
let voice_state = guild.voice_states.get(&message.user.id)
    .unwrap_or_else(|| panic!("User's voice state not found"));
let channel_id = voice_state.unwrap_or_else(|| panic!("Id not present"));
// ....
```

**Comment by teamplz** [comment]
Awesome thanks!

**Comment by Sebbl0508** [comment]
How does this work with slash commands?  
I haven't found any other way than getting the `guild_id` and using `to_guild_cached(&ctx.cache)`.  
But i only returns `None` for me, probably because this guild isn't in cache or something.

Is there a way to get a full `Guild` when working with slash commands?

**Comment by GnomedDev** [comment]
Enable the GUILDS intent and all guilds will be in cache even with slash commands. In future, questions like this should be asked in https://discord.gg/serenity-rs instead of necrobumping issues.
