### ISSUE TITLE
create_channel does not work with ChannelType::Category

### ISSUE THREAD

**Issue by not-inept** [zeyla/serenity#199]
I was attempting to create a category using `serenity::model::GuildId::create_channel`:
```rust
let guild = msg.guild_id().unwrap();
let res = guild.create_channel("test-category", ChannelType::Category);
match res {
    Ok(e) => println!("Worked out because {}", e),
    Err(e) => println!("Failed because of {}", e)
}
```
`create_channel` works with the other channel types, and seems to only fail with ChannelType::Category.

Looking a step deeper, I tried creating a category with `serenity::http::create_channel`, mirroring what is done in `GuildId::create_channel`:
```rust
let guild = msg.guild_id().unwrap();
let _category = create_channel(guild.0, &json!({
    "type": ChannelType::Category.name(),
    "name": "voice-category".to_string(),
}));
```
As should be expected, this also fails.

However, again, switching to a different type works fine:
```rust
let guild = msg.guild_id().unwrap();
let _voice = create_channel(guild.0, &json!({
    "type": ChannelType::Voice.name(),
    "name": "voice-category".to_string(),
}));
```
If I switch out the `ChannelType::Category` with `4` or `ChannelType::Category as i64` I am able to create a category.

**Comment by acdenisSK** [comment]
Ah yeah, `type` doesn't have a string based "category" type like "voice` and "text" do. Although seems a bit stupid for the `create_channel` to be using the `name` function instead of their actual integer values.
Anyway will fix this in a moment.

**Comment by acdenisSK** [comment]
[`e57b510`](https://github.com/zeyla/serenity/commit/e57b510edd640abb243664337a1c163924313612).
