### ISSUE TITLE
Bot cannot connect

### ISSUE THREAD

**Issue by Lakelezz** [zeyla/serenity#203]
Every commit after #195 causes my bot to be unable to connect. #195 itself does not compile according to Travis.

Here is what the command-line prints with `RUST_LOG = WARN`:
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Gateway(BuildingUrl)', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
WARN:serenity::client::bridge::gateway::shard_manager: Failed to send shutdown to shard queuer: "SendError(..)"`

Despite removing the `unwrap()` (as mentioned in the error) from `connect()`'s `Result<WsClient>`, Serenity never reconnects to begin with.

Every commit prior #195 works, hence my suspicion that this commit, which affects Shards/`connect()`, broke Serenity.

**Comment by zeyla** [comment]
Closed by 585ac6e6ca792facf29063776c83262fa849161b.
