### ISSUE TITLE
Add #[derive(Debug)] to DispatchError

### ISSUE THREAD

**Issue by UninterestinAcc** [zeyla/serenity#204]
I've been trying to debug by printing out the DispatchError (mildly bad practice) but it isn't working very well for me, so I suggest making it easier by letting the rust formatter format it into a string by `{:?}`

File / line number in question: src/framework/standard/mod.rs#L106

**Comment by acdenisSK** [comment]
[`a58de97`](https://github.com/zeyla/serenity/commit/a58de97e6089aa98f04d2cdc7312ed38a9f72b22)

**Comment by UninterestinAcc** [comment]
Woops didn't notice #173 already exists...
