### ISSUE TITLE
failed to load source for a dependency on `serenity`

### ISSUE THREAD

**Issue by hurnhu** [zeyla/serenity#216]
Hello, I tried building a program I am working on and got the following error.
Last time i worked on this project (~20 days ago) i was not getting this error, any ideas?
``` >cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/zeyla/serenity.git`
error: failed to load source for a dependency on `serenity`

Caused by:
  Unable to update https://github.com/zeyla/serenity.git

To learn more, run the command again with --verbose.
```
Cargo.toml
```
[dependencies]
rand = "0.3.15"
chrono = "0.4"
serde = "1.0.16"
serde_json = "1.0.4"
serde_derive = "1.0.16"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
features = ["framework", "standard_framework"]
```

**Comment by Lakelezz** [comment]
Serenity does not use the master-branch anymore.
Try the following in your `cargo.toml`:
`[dependencies.serenity]
git = "https://github.com/zeyla/serenity/"
branch = "v0.5.0"`
Make sure to replace the right version-number.

**Comment by zeyla** [comment]
Resolved as we now have a master branch again, which maps to the most recently released version.
