### ISSUE TITLE
Hello we will be using this 

### ISSUE THREAD

**Issue by MrJacz** [zeyla/serenity#221]

**Comment by MrJacz** [comment]
Everyone u can now talk

**Comment by Aetheryx** [comment]
<@285147073115062282> stinky

**Comment by Technach** [comment]
discord 2

**Comment by MrJacz** [comment]
LOL

**Comment by Thewsomeguy** [comment]
hello

**Comment by Jackzmc** [comment]
rude

**Comment by Pandentia** [comment]
@MrJacz stop creating issues on various repositories. Thank you.

**Comment by Aetheryx** [comment]
@everyone @here suh dud

**Comment by PassTheMayo** [comment]
lol hi

**Comment by MrJacz** [comment]
let us fuck around while we can pls

**Comment by lorpus** [comment]
ayyo

**Comment by Technach** [comment]
still not closed :(

**Comment by Mstrodl** [comment]
To be fair, you have to have a very high IQ to understand Discord API. The humour is extremely subtle, and without a solid grasp of horse dildos most of the jokes will go over a typical Discord.NET programmer's head. There’s also Danny's nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they’re not just funny- they say something deep about LIFE. As a consequence people who dislike Discord API truly ARE idiots- of course they wouldn’t appreciate, for instance, the humour in Danny's existential catchphrase “!ban” which itself is a cryptic reference to Turgenev’s Russian epic Fathers and Sons. I’m smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Danny's genius wit unfolds itself on their computer monitors. What fools.. how I pity them. 😂

And yes, by the way, i DO have a Bad Dragon tattoo. And no, you cannot see it. It’s for the ladies’ eyes only- and even then they have to demonstrate that they’re within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid 😎
