### ISSUE TITLE
Allow non-bot user tokens

### ISSUE THREAD

**Issue by mateon1** [zeyla/serenity#257]
I would like to use this library to write a custom discord client, but the `Client::new` method only accepts bot tokens.

Would it be possible to just add a `Client::user_new` method to allow connecting as a normal user? Or would larger changes need to be made?'

**Comment by zeyla** [comment]
Sorry, we support neither the automating of user accounts or third party client creation because it is [forbidden by Discord](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-). Taken from the [API Terms of Service](https://discordapp.com/developers/docs/legal):
```
2.2 Restrictions. You shall not, and shall not permit any person, directly or 
indirectly, to (i) reverse engineer, disassemble, reconstruct, decompile,
translate, modify or copy the API
```

**Comment by Coding-Doctors** [comment]
BTW that section is talking specifically about doing those actions to the **API & SDK**, as in you can't reverse engineer, disassemble, reconstruct, decompile, translate, modify the **API & SDK**. That section doesn't apply to the service. IIRC Discord only experissly forbids user bots and automating the login process (for example taking a users email and login, then using the API to get a token would qualifiy for that). Third Party clients are still discouraged to the best of my knowladge, there is nothing offical expressly forbidding the creation thereof one, so long as it compiles to all set terms, including those of the API.

**Comment by zeyla** [comment]
Third party clients are also against the terms of service. Besides, they
can terminate your account for any reason:

"The Company reserves the right to refuse any user access to the Services
without notice for any reason, including but not limited to a violation of
the Terms"
<https://discordapp.com/terms>

**Comment by Coding-Doctors** [comment]
The termination for any reason is indeed in the ToS, however not listed in seemingly any way are lines forbidding third party clients.

**Comment by b1naryth1ef** [comment]
Zeyla is correct. To use the service you must interact with the API, so those terms apply. Connecting to Discord via an unsupported or third-party client counts as automating the API outside of our expressed permission, and thus can get you banned for ToS violations.

**Comment by Coding-Doctors** [comment]
@b1naryth1ef Thanks for the clearification, struggling through legal terminology can be tough sometimes without explict clearification, wish it was layed out more clear elsewhere (though I may have missed something).
