### ISSUE TITLE
add fallback for unrecognized command to `StandardFramework`

### ISSUE THREAD

**Issue by mammothbane** [zeyla/serenity#275]
It'd be nice if there was a way to be able to handle unrecognized commands through the `StandardFramework` interface. Currently, as far as I can tell, you'd need to catch these with `EventHandler::message` or roll your own `Framework`.

My suggestion would be to add a method to the `StandardFramework` builder; something like this:

```rust
let framework = StandardFramework::new();

framework
    .on("my_command", |_c, msg, _| msg.reply("something!"))
    .unrecognized_command(|_c, msg, _args| msg.reply("something else!");
```

This could make e.g. #274 into a utility function that could be plugged into `StandardFramework::unrecognized_command`.

**Comment by acdenisSK** [comment]
Added in [c:293779](https://github.com/zeyla/serenity/commit/29377922d3d79848efcb8d3bd0fbd52c21e81c5d).
