### ISSUE TITLE
`ffmpeg` sources leak zombie processes

### ISSUE THREAD

**Issue by FelixMcFelix** [zeyla/serenity#277]
Noticed this after running [felyne](https://github.com/felixmcfelix/felyne-bot) last night, and returning to find ~30 000 zombie processes. The bot I'm working with plays many short-lived sounds to completion, but keeps at most 2 active sounds. This is verified by monitoring the amount of sounds queued up in the audio thread.

The issue seems to stem from [an implementation detail of Child](https://doc.rust-lang.org/std/process/struct.Child.html):
> There is no implementation of Drop for child processes, so if you do not ensure the Child has exited then it will continue to run, even after the Child handle to the child process has gone out of scope.

Naturally all we'd need would be a custom `impl Drop` for `ChildContainer`, but this would also be alleviated by moving to e.g. [rust-ffmpeg](https://github.com/meh/rust-ffmpeg).

I'd be happy to work on this, although I'm not sure which avenue you'd prefer.

**Comment by zeyla** [comment]
Closed by #278
