### ISSUE TITLE
On guild_create, calling chunk_guilds offsets heartbeats and doesn't update cache

### ISSUE THREAD

**Issue by jkcclemens** [zeyla/serenity#289]
I'm trying to get the offline members of a large guild. See [the code](https://github.com/jkcclemens/lalafell_bot/blob/0db04b2ede258fd4df9769a6007d5e052ad6758a/src/listeners/guilds_ext.rs#L18) (also below).

```rust
  fn guild_create(&self, ctx: Context, guild: Guild, new: bool) {
    if new || !guild.is_large() {
      return;
    }

    info!("Asking for offline members of {} ({})", guild.name, guild.id);
    ctx.shard.chunk_guilds(vec![guild.id], None, None);
  }
```

Is calling `chunk_guilds` on `guild_create` not valid? Otherwise, the cache is not updated with offline members, and `guild.members` does not contain offline members. I also get this warning:

```
[13:59:59] [INFO] lalafell_bot::listeners::guilds_ext – Asking for offline members of lala world (307359970096185345)
[13:59:59] [WARN] serenity::gateway::shard – [Shard [0, 1]] Heartbeat off; them: 5, us: 3
```

This is on 0.5.1 and `rustc 1.26.0-nightly (2789b067d 2018-03-06)`.

**Comment by jkcclemens** [comment]
Any news on this? This is a very, very annoying bug that breaks functionality in my bot. Unless [what I'm doing](https://github.com/jkcclemens/lalafell_bot/blob/dev/src/listeners/guilds_ext.rs#L18) is wrong, this should be looked at.

**Comment by zeyla** [comment]
I apologize for the (very) late reply.

fd77a91 should fix this.
