### ISSUE TITLE
Make `ChannelId` indexable

### ISSUE THREAD

**Issue by ForsakenHarmony** [zeyla/serenity#294]
I can't even find it manually, would it be possible to just define the base struct without whatever (I'm assuming) macro?

**Comment by zeyla** [comment]
`ChannelId` is a tuple-struct with a single value (<https://rustbyexample.com/custom_types/structs.html>). You can create one via `ChannelId(7)` or your equivalent value.

**Comment by ForsakenHarmony** [comment]
Where is it defined though? I can't find it, neither can my ide

**Comment by zeyla** [comment]
https://docs.rs/serenity/0.5.1/serenity/model/id/struct.ChannelId.html

**Comment by ForsakenHarmony** [comment]
```rs
id_u64! {
    /// An identifier for an Application.
    ApplicationId;
    /// An identifier for a Channel
    ChannelId;
...
```

in a macro as I said, really bad for someone wanting to use autocomplete 
but ¯\\\_(ツ)_/¯

**Comment by ForsakenHarmony** [comment]
like you could move the `pub struct $name(pub u64);` out and leave the rest in the macro
