### ISSUE TITLE
Compile Error?

### ISSUE THREAD

**Issue by MggMuggins** [zeyla/serenity#308]
I'm working on a bot ([code_runner](https://github.com/MggMuggins/code_runner)) that does some fancy stuff. I'm working with both my laptop (for development) and a server (for testing/deployment). I'm getting a compile error on the server and not on my laptop. This is only after having run `cargo update` on the repo. The serenity version is `0.5.2`.

Lappy:
``` sh
$ rustc -V
rustc 1.26.0-nightly (9c9424de5 2018-03-27)
```
Server:
```sh
 $ rustc -V
rustc 1.22.1
```

Here's the error:
```
error: expected one of `,` or `as`, found `::`
 --> /home/Samwise/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.5.2/src/internal/ws_impl.rs:6:12
  |
6 |     message::OwnedMessage,
  |            ^^ expected one of `,` or `as` here

error: expected one of `;` or `as`, found `::`
 --> /home/Samwise/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.5.2/src/internal/ws_impl.rs:6:12
  |
6 |     message::OwnedMessage,
  |            ^^ expected one of `;` or `as` here
```

**Comment by Lakelezz** [comment]
You need to update your server to latest stable Rust, nested imports are a new thing.

**Comment by MggMuggins** [comment]
I see. Thanks!
