### ISSUE TITLE
No event for when a member first joins a server

### ISSUE THREAD

**Issue by Redrield** [zeyla/serenity#312]
At the moment in Serenity, it seems as though there is no way to add an event handler for when a user first joins the server. This is something that can be done, as it is done by [this](https://github.com/Rapptz/discord.py/blob/async/examples/new_member.py) example of discord.py

**Comment by Noxime** [comment]
I think [this](https://docs.rs/serenity/0.5.3/serenity/client/trait.EventHandler.html#method.guild_member_addition) is what you are looking for. You can see [here](https://github.com/zeyla/serenity/blob/master/examples/03_struct_utilities/src/main.rs) how to use the `EventHandler`

**Comment by Redrield** [comment]
This is called when a user joins the server? I'm not familiar with the terminology in discord's API

**Comment by Noxime** [comment]
Yes, internally and among developers discord servers are called Guilds

**Comment by Redrield** [comment]
Ah, thanks
