### ISSUE TITLE
Finish serde_derive impl

### ISSUE THREAD

**Issue by zeyla** [zeyla/serenity#63]
Finish up the work on the `serde` branch, which mostly involves writing a few custom deserializers: <https://github.com/zeyla/serenity/tree/serde>

**Comment by indiv0** [comment]
I hereby claim this territory in the name of open source.

**Comment by zeyla** [comment]
Due to incoming changes, I'll do this issue instead.

**Comment by indiv0** [comment]
Okey doke.

**Comment by zeyla** [comment]
Closed by 8946e39.
